openapi: "3.0.3"
info:
  title: "ZIPs REST API"    
  description: "My First API"
  version: "v1.0"


servers:
  - url: http://localhost:3000
    description: "Development server"

components:
  schemas:  
   city: 
    type: object
    properties: 
        Id:
          type: string
        description: Id
        city:
          type: strin
          description: City name
        loc: 
           type: array
           items:
            type: number
            maxItems: 2
            minItems: 2
        pop:
            type: number
            minimum: 10
        state:
          type: string
          enum: [
          "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ",
"PA", "DE", "DC", "MD", "VA", "WV", "NC", "SC",
"GA", "FL", "AL", "TN", "MS", "KY", "OH", "IN",
"MI", "IA", "WI", "MN", "SD", "ND", "MT", "IL",
"MO", "KS", "NE", "LA", "AR", "OK", "TX", "CO",
"WY", "ID", "UT", "AZ", "NM", "NV", "CA", "HI",
"OR", "WA", "AK"
]
  
  
paths:
  /api/states:
      get:
      description: Get a list of all the state
      



       




paths: 
    /api/states:
      get: 
      description: Get a list of all the states
      operationId: getStates
      responses:
          200:
          description: Default result representation 
          content:
            application/json: 
              schema:
                type: array
                items:
                  type: string
            